
api_version = "2025-10"

[[extensions]]

uid = "83cc8ae9-211f-e46d-144b-da561d6afa7232396926"

type = "ui_extension"
name = "Checkout Address +"
handle = "checkout-address-field"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"
[extensions.capabilities]
block_progress = true

network_access = true
api_access = true

[extensions.settings]

[[extensions.settings.fields]]
key = "block_title"
type = "single_line_text_field"
name = "Block Title"
default = "Barangay and Zip Code"

[[extensions.settings.fields]]
key = "country_code"
type = "single_line_text_field"
name = "Country code"
default = "PH"

[[extensions.settings.fields]]
key = "addresses_file_url"
type = "single_line_text_field"
name = "Addresses File URL"

# Label settings
[[extensions.settings.fields]]
key = "label_region_ENG"
type = "single_line_text_field"
name = "Region Label (English)"
default = "Region"

[[extensions.settings.fields]]
key = "label_city_ENG"
type = "single_line_text_field"
name = "City Label (English)"
default = "City"

[[extensions.settings.fields]]
key = "label_district_ENG"
type = "single_line_text_field"
name = "District Label (English)"
default = "District"

[[extensions.settings.fields]]
key = "label_zipcode_ENG"
type = "single_line_text_field"
name = "Zipcode Label (English)"
default = "Zipcode"

# Target save note keys for storing the selected values
[[extensions.settings.fields]]
key = "target_save_note_key_for_Region"
type = "single_line_text_field"
name = "Target Save Note Key for Region"
default = "Region"

[[extensions.settings.fields]]
key = "target_save_note_key_for_city"
type = "single_line_text_field"
name = "Target Save Note Key for City"
default = "City"

[[extensions.settings.fields]]
key = "target_save_note_key_for_district"
type = "single_line_text_field"
name = "Target Save Note Key for District"
default = "District"

[[extensions.settings.fields]]
key = "target_save_note_key_for_zipcode"
type = "single_line_text_field"
name = "Target Save Note Key for Zipcode"
default = "Zipcode"