# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4e30806d7b402f48f411da31abbfe36f"
name = "SOGO ID Address Fields"
handle = "sogo-id-address-fields"
application_url = "https://example.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "ahmadkemana.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_products,read_script_tags,write_customers,write_discounts,write_orders,write_products,write_script_tags"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
